### ISSUE TITLE
compiling failure

### ISSUE THREAD

**Issue by SzotsGabor** [spamdrew128/Bitboard_Chess_Engine#59]
Hi Andrew,

I tried to compile it this way:

gcc *.c TDD/*.c TDD/ENGINE_TESTS/*.c TDD/TESTS/*.c SRC/BITBOARDS/*.c SRC/ENDINGS/*.c SRC/ENGINE/*.c SRC/FEN/*.c SRC/LOOKUP/*.c SRC/MOVEGEN/*.c SRC/PLAY/*.c SRC/RNG/*.c SRC/STATE/*.c SRC/TIMER/*.c SRC/UCI/*.c SRC/ZOBRIST/*.c -I.\ -ISRC -ISRC/BITBOARDS -ISRC/ENDINGS -ISRC/ENGINE -ISRC/FEN -ISRC/LOOKUP -ISRC/MOVEGEN -ISRC/PLAY -ISRC/RNG -ISRC/STATE -ISRC/TIMER -ISRC/UCI -ISRC/ZOBRIST -ITDD -ITDD/ENGINE_TESTS -ITDD/TESTS -O3 -flto -march=native -oApotheosis_1.0.1-x64-SzG.exe

However, I get this error message:

-mingw32/bin/ld.exe: C:\Users\szots\AppData\Local\Temp\cc5bqcX7.o (symbol from plugin):(.text+0x0): multiple definition of `main'; C:\Users\szots\AppData\Local\Temp\cc5SkBlD.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status

Any hints? Please note that I am not a programmer, just have basic skills to use MINGW2/GCC.

**Comment by spamdrew128** [comment]
Hmm. Did you try running `sh release.sh`? If you have the ability to run that file it should compile. If not just copy the command inside of it which is `make EXE=ApotheosisV1.0.1 RELEASE=y`. If you still have issues let me know but hopefully this fixes it because I am also not good at compilation stuff.

**Comment by SzotsGabor** [comment]
> Hmm. Did you try running `sh release.sh`? If you have the ability to run that script it should compile the engine. If not just copy the command inside of it which is `make EXE=ApotheosisV1.0.1 RELEASE=y`. If you still have issues let me know but hopefully this fixes it because I am also not good at compilation stuff.

Yes the make worked but it had worked also without release=y. Only, when it displays its lines after the uci command, the letters appear very slowly one after the other. Same with your compile which now runs after I told Windows Defender not to delete it (which it did several times).

The sh thing does not work, the OS does not recognize the sh command. But it doesn't matter.

**Comment by spamdrew128** [comment]
“RELEASE=y” is simply to tell the compiler to remove the assert statements in my code using the -DNDEBUG cflag, so it’s not completely necessary. Not sure if why it would run really slowly when responding to the uci command though…
